apiVersion: v1
kind: Service
metadata:
  name: sys-info-app-service
spec:
  selector:
    app: sys-info-app # This MUST match the label in your Deployment
  ports:
    - protocol: TCP
      port: 5000         # The port the Service listens on
      targetPort: 5000   # The port the Container is listening on
  type: NodePort